return {
	["Priority1"] = {"Class D", "Chaos Insurgency"}, --Class D and Hostile teams
	["Priority2"] = {"Security Department", "MTF Beta-7", "MTF Epsilon-11", "MTF Nu-7", "Intelligence Agency", "Scientific Department", "Medical Department","Janitor"}, -- Normal foundation teams
	["Priority3"] = {"RAISA", "Ethics Committee", "Site Director", "Administrative Department", "MTF Omega-1", "MTF Alpha-1","Internal Security Department"} -- TK Foundation teams
}
